<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Wpe.App</RootNamespace>
    <AssemblyName>WinsockPacketEditor</AssemblyName>
    <ApplicationIcon>Assets\wpe.ico</ApplicationIcon>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <!-- 允许在非 Windows 机器上进行编译校验（不影响 Windows 构建） -->
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wpe.Core\Wpe.Core.csproj" />
  </ItemGroup>

</Project>
